### ISSUE TITLE
Fails with perls built with -Duselongdouble

### ISSUE THREAD

**Issue by andk** [KJ7LNW/perl-PDL-IO-Touchstone#1]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/cb25e1ba-04a7-11ed-9ce0-95be7a3021a8

**Comment by KJ7LNW** [comment]
Fixed in 1.002 pending smoke tests.

**Comment by KJ7LNW** [comment]
Looks like its working with -ld builds: http://www.cpantesters.org/cpan/report/97300a1a-1641-11ed-8aeb-5b1e8b1e929d

Thanks @andk for the report!
