### ISSUE TITLE
v1.002 fails to declare dependency on PDL::LinearAlgebra

### ISSUE THREAD

**Issue by mohawk2** [KJ7LNW/perl-PDL-IO-Touchstone#2]
This causes an attempt to install it (as PDL's "downstream" CI does) to fail.

**Comment by mohawk2** [comment]
For now, disabling in PDL's CI: https://github.com/PDLPorters/devops/commit/8c0ce761e18670900b1740e0a87e74310d43db20

**Comment by KJ7LNW** [comment]
Thank you for noticing that!  Would be nice to make a test for that.  I've uploaded 1.003 to PAUSE with the fix and git is up to date, too.  Please give CI a try and see if it succeeds.

**Comment by mohawk2** [comment]
The CI has worked, as you can see yourself by looking at the list of commits (top right of repo front page, where it says (currently) "24 commits"), which have ticks by them.
